config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show', to: 'dashboard#show'

  resources :instruments do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: :index
  devise_for :users
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :instrument
  belongs_to :user
  validates :start_date, :end_date, presence: true
  enum status: [:pending, :accepted, :denied]
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :name, :category, :description, :address, :price, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search_by_name_and_category_and_description,
    against: [:name, :category, :description],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :instruments, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :store_location
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private


  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # this allows the user to add a first name and last name on sign up
    #we sould need to manually add these fields into our fsign up form
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    #this line controls all the fields the user can add to their profile for example bio or name
    # edit the array that contains :username with any other columns you want to add to users table i.e. :bio
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

#   def store_location
#   # session[:previous_urls] ||= []
#   # store unique urls only
#   session[:previous_urls].prepend request.fullpath if session[:previous_urls].first != request.fullpath
#   # For Rails < 3.2
#   # session[:previous_urls].unshift request.fullpath if session[:previous_urls].first != request.fullpath
#   session[:previous_urls].pop if session[:previous_urls].count > 2
# end
# def after_sign_in_path_for(resource)
#   session[:previous_urls].last || root_path
# end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @instruments = current_user.instruments
    @bookings = policy_scope(current_user.bookings)
  end

  def new
    @booking = Booking.new
    @instrument = Instrument.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @instrument = Instrument.find(params[:instrument_id])
    authorize @instrument
    @booking.instrument = @instrument
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      redirect_to instrument_path(@instrument)
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
  end

  def destroy
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :instrument)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_after_action :verify_authorized
  def show
    @instruments = current_user.instruments
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
  if params[:address]
    @instruments = policy_scope(Instrument).near(params[:address], 10)
  elsif params[:type]
    @instruments = policy_scope(Instrument)
    .search_by_name_and_category_and_description(params[:type])
  else
    @instruments = policy_scope(Instrument).first(10)
  end
    @markers = @instruments.map do |instrument|
      {
        lat: instrument.latitude,
        lng: instrument.longitude,
        infoWindow: render_to_string(partial: "shared/info_window", locals: { instrument: instrument })
      }
    end
  end

  def show
    @instrument = Instrument.find(params[:id])
    @booking = Booking.new
    authorize @instrument
  end

  def new
    @instrument = Instrument.new
    authorize @instrument
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user_id = current_user.id
    authorize @instrument
    if @instrument.save
      redirect_to dashboard_show_path
    else render 'new'
    end
  end

  def edit
    authorize @instrument
  end

  def update
    @instrument.update(instrument_params)
    authorize @instrument
    redirect_to dashboard_show_path
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy
    authorize @instrument
    redirect_to dashboard_show_path
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  def instrument_params
    params[:instrument].permit(:name, :category, :description, :price, :address, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 Your booking request is successfully sent!</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>
  <h1>My bookings</h1>
  <% @bookings.each do |booking| %>
    <div class="notification">
      <p><%= booking.status %></p>
       <% if booking.instrument.photo.file %>
          <%= cl_image_tag booking.instrument.photo, size: "200x200" %>
          <% else %>
          <%= image_tag 'record-player.png',size: "200x200" %>
          <% end %>

      <div class="notification-content">
        <p><small><%= booking.instrument.name %></small></p>
        <p><%= booking.instrument.description %></p>
      </div>
      <div class="notification-date">
        <p>Dates:</p>
        <p><%= booking.start_date %></p>
        <p><%= booking.end_date %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/dashboard/show.html.erb
<div class="dash">
  <ul class="nav nav-tabs mt-3 ml-4" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">My listings</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Requests received</a>
    </li>
  </ul>
  <div class="tab-content mt-4 mx-5" id="myTabContent">
    <div class="tab-pane fade show active" id="contact" role="tabpanel" aria-labelledby="contact-tab">
      <div class="main-container">
        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
        </div>
      </div>
      <div class="d-flex flex-center mb-2">
        <%= link_to new_instrument_path do %>
        <p class="button-orange"> List an instrument</p>
        <% end %>
      </div>
      <div class="user-dashboard-cards">
        <% @instruments.each do |instrument| %>
        <div class="card">
          <%= link_to instrument_path(instrument) do %>
          <% if instrument.photo.file %>
          <%= cl_image_tag instrument.photo, size: "300x200" %>
          <% else %>
          <%= image_tag 'record-player.png', size: "300x200" %>
          <% end %>
          <div class="card-info">
            <div class="card-description">
              <h3><%= instrument.name %></h3>
              <p><%= truncate(instrument.description, length: 80) %></p>
            </div>
            <div class="card-price">
              <p><%= instrument.price %> €</p>
            </div>
            <div id="edit-instrument">
              <%= link_to "Edit", edit_instrument_path(instrument) %>
            </div>
            <div id="delete-instrument">
              <%= link_to "Delete", instrument_path(instrument), method: :delete %>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
     <!--  <% @instruments.each do |instrument| %>
      <div class="notification">
        <%= link_to instrument_path(instrument) do %>
        <% if instrument.photo.file %>
        <%= cl_image_tag instrument.photo, size: "200x200" %>
        <% else %>
        <%= image_tag 'record-player.png',size: "200x200" %>
        <% end %>
        <% end %>
        <div class="notification-content">
          <%= link_to instrument_path(instrument) do %>
          <p><small><%= instrument.name %></small></p>
          <p><%= instrument.description %></p>
        </div>
        <% end %>
        <div>
          <i class="fas fa-check-circle px-2"></i>
          <i class="fas fa-times-circle px-2"></i>
        </div>
        <%= link_to instrument_path(instrument) do %>
        <div class="notification-date pl-2">
          <p>Dates:</p>
          <p><%= instrument.user.bookings[0].start_date %></p>
          <p><%= instrument.user.bookings[0].end_date %></p>
        </div>
        <% end %>
        <p class="pl-2"><%= instrument.user.email %></p>
      </div> -->
    <!--   <% end %> -->
    </div>
  </div>
</div>

app/views/instruments/edit.html.erb
<div class="form-container">
  <h1>Edit Your Instrument</h1>
  <%= render "shared/form" %>
  <div class="back">
    <%= link_to "Back", instruments_path %>
  </div>
</div>

app/views/instruments/index.html.erb
<div class="filter-header">
   <h1>Instruments in <strong> <%= params[:address].capitalize %> </strong></h1>
 </div>
<div class="filters">
 <div class="location-search">
   <div class="search-form">
     <form action="/instruments" accept-charset="UTF-8" method="get">
       <input name="utf8" type="hidden" value="&#x2713;" />
       <input type="text" name="address" id="query" placeholder="City" class="main-search form-control form-input" />
       <input type="submit" name="commit" value="Refresh" id="submit-search" data-disable-with="Search" class="form-control" />
     </form>
   </div>
 </div>
 <div class="item-search">
   <form action="/instruments" accept-charset="UTF-8" method="get" class="">
     <input name="utf8" type="hidden" value="&#x2713;"/>
     <!-- <input type="text" name="type" id="query" placeholder="Type of instrument" class="main-search form-control form-input" /> -->
     <input type="hidden" id="query" name="address" value="<%= params[:address] %>" class="form-control">
     <!-- <input type="submit" name="commit" value="Filter" id="submit-search" data-disable-with="Search" /> -->
   </form>
 </div>
</div>
<div class="mapbox">
    <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
<div class="main-container">
  <div class="cards">
    <% @instruments.each do |instrument| %>
      <div class="card">
        <%= link_to instrument_path(instrument) do %>
          <div class="item-photo">
            <% if instrument.photo.file %>
              <%= cl_image_tag instrument.photo, size: "200x200" %>
            <% else %>
           <%= image_tag 'record-player.png', size: "200x200" %>
            <% end %>
            </div>
          <div class="card-info">
            <div class="card-description">
              <h3><%= instrument.name %></h3>
              <p><%=h truncate(instrument.description, length: 30) %></p>
            </div>
            <div class="card-price mt-2">
              <p><%= instrument.price %> €/day</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>

app/views/instruments/new.html.erb
<div class="form-container">
  <div class="form-headline">
    <h1>List your instrument</h1>
      </div>
        <%= render "shared/form" %>
      <div class="back">
      <%= link_to "Back", instruments_path %>
    </div>
</div>

app/views/instruments/show.html.erb
<div class="show-header">
  <div class="back-to">
    <a class="" href="/instruments"><i class="fas fa-chevron-left"></i> Back to search results</a>
  </div>
    <div class="heading"></div>
      <h2><%= @instrument.name %></h2>
</div>
<div class="show-container"> <!-- grid container -->
<!--   item one in grid -->
  <div class="show-card">
    <% if @instrument.photo.file  %>
      <div class="show-image">
        <%= cl_image_tag(@instrument.photo) %>
      </div>
    <% else %>
      <%= image_tag 'record-player.png', class: "no-photo" %>
    <% end %>

  </div>
<!--   item 3 in grid
 -->   <div class="show-card-info">
      <p>This <%= @instrument.category %> is located at <%= @instrument.address %></p>
      <p>It costs <%= @instrument.price  %>€/day to rent</p>
      <p><%= @instrument.description %></p>

    </div>
<!--   item 2 in grid -->
  <% if @instrument.user == current_user %>
  <div class="user-action-box item2">
    <div class="user-actions">
      <p>You listed this instrument on <%= @instrument.created_at %></p>
      <p>If you would like to modify your listing, click on one of the links below</p>
     <div class="crud-links">
      <%= link_to "Edit",edit_instrument_path(@instrument) %>
       <%= link_to "Delete", instrument_path(@instrument), method: :delete, data: {confirm: "Are you sure?"} %>
      </div>
    </div>
  </div>
  <% else %>
  <div class="book-container item2">
    <div class="book-form">
      <%= simple_form_for [@instrument, @booking] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <input type="submit" name="commit" value="Book Now!" class="button-orange" data-disable-with="Book Now!" />
      </div>
  </div>
    <% end%>
  <% end %>
<!--   end of grid -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Instrurent</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hp-container">
  <div class="landing-container">
    <h1><span id="firsthalf">Instru</span><span id="secondhalf">Rent</span></h1>
         <h3>Top quality instruments for rent, made affordable. </h3>
          <h5>Where are you looking for an instrument?</h5>

      <div class="search-form">
      <form action="/instruments" accept-charset="UTF-8" method="get">
        <input name="utf8" type="hidden" value="&#x2713;" />
        <input type="text" name="address" id="query" class="search-form" placeholder="Try  'Berlin'" />
        <div id="main-search">
          <input type="submit" name="commit" value="Search" data-disable-with="Search" />
        </div>
      </form>
    </div>
  </div>

<div class="how-it-works-container">
  <h2 class="text-center"> How It Works </h2>
      <div class="cards-howitworks">
       <div class="card-howitworks">
        <img src="https://image.flaticon.com/icons/svg/182/182336.svg" alt="">
        <div>
          <h2>1. Enter Your City </h2>
          <p>Enter your city to find instruments near you.</p>
        </div>
       </div>

        <div class="card-howitworks">
          <div>
             <img src="https://image.flaticon.com/icons/svg/1987/1987042.svg" alt="">
            <h2>2. Choose an Instrument</h2>
            <p>Select from hundreds of high quality musical instruments.</p>
          </div>
        </div>

        <div class="card-howitworks">
        <div>
        <img src=https://image.flaticon.com/icons/svg/1244/1244363.svg alt="">
          <h2>3. Book Your Instrument</h2>
          <p>Send a request to the lender. Enjoy playing!</p>
        </div>
      </div>
</div>

 <div class="testimonials-container">
  <div class="testimonial-image">
  <img src="https://images.unsplash.com/photo-1523469790366-9429dfc437bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80" alt="">
  </div>
    <div class="testimonial-copy">
     <p> "I always wanted to try out playing a guitar! I could easily rent one at low cost and high quality and start
     learning without a big investment!"</p>
     <h5> Mark, Berlin </h5>
    </div>
  </div>

<div class="benefits-container">
  <h2 class="text-center"> Why InstruRent?</h2>
   <div class="cards-benefits">
       <div class="card-benefits">
          <img src="https://image.flaticon.com/icons/svg/584/584093.svg" alt="">
        <div>
          <h3>Save Money</h3>
          <p>Learn to play an instrument without a big investment.</p>
        </div>
       </div>

        <div class="card-benefits">
          <div>
             <img src="https://image.flaticon.com/icons/svg/599/599956.svg" alt="">
            <h3> Make Your Event Memorable</h3>
            <p>No need to buy that expensive vinyl player for a one time party or wedding!</p>
          </div>
        </div>

        <div class="card-benefits">
        <img src="https://image.flaticon.com/icons/svg/1611/1611179.svg" alt="">
        <div>
          <br>
          <h3>Earn Money</h3>
          <br>
          <p>Make extra money by lending out your belongings!</p>
        </div>
      </div>
   </div>
</div>

 <div class="footer">
      <p>Made with ♥️ at Le Wagon </p>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="crud-form">
  <%= simple_form_for(@instrument) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <% if @instrument.errors.any? %>
      <ul>
        <% @instrument.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :category, collection: ["Accordion",
"Bagpipes",
"Banjo",
"Bass guitar",
"Bassoon",
"Bells",
"Bongo",
"Castanets",
"Cello",
"Clarinet",
"Cornet",
"Cymbal",
"Didgeridoo",
"Double bass",
"Drum kit",
"Electric Guitar",
"Flugelhorn",
"Flute",
"French horn",
"Glockenspiel",
"Gong",
"Guitar",
"Harmonica",
"Harp",
"Harpsichord",
"Kazoo",
"Mandolin",
"Maracas",
"Marimba",
"Mbira",
"Oboe",
"Ocarina",
"Organ",
"Pan Pipes",
"Pennywhistle",
"Piano",
"Piccolo",
"Pitch Pipe",
"Recorder",
"Saxophone",
"Sitar",
"Steelpan",
"Synthesizer",
"Tambourine",
"Timpani",
"Triangle",
"Trombone",
"Trumpet",
"Tuba",
"Ukulele",
"Viola",
"Violin",
"Xylophone",
"Zither",
"Other"] %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.input :price %>
    </div>
    <div class="form-actions">
      <input type="submit" name="commit" value="List your Instrument" class="button-orange" data-disable-with="List your Instrument">
      </div>
  <% end %>
  </div>

app/views/shared/_info_window.html.erb
<div class="card" id="smaller-card">
  <%= link_to instrument_path(instrument) do %>
    <%= cl_image_tag instrument.photo %>
      <div class="card-description">
          <h3><%= instrument.name %></h3>
        </div>
        <div class="card-price">
          <p><%= instrument.price %> €</p>
        </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "guitar-pick.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "List an instrument", new_instrument_path, id: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My Bookings", bookings_path, id: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to "My Listings", dashboard_show_path, id: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit My Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "List an instrument", new_instrument_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "List an instrument", new_instrument_path, id: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, id: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>